export {default as Navbar} from './Navbar'
export {default as CardPopular } from './CardPopular'
export { default as GigsCard} from './GigsCard'
export {default as Category} from './Category'
export {default as Certified} from './Certified'
export {default as Testimony} from './Testimony'
export {default as LastExperiencesCard} from './LastExperincesCard'
export {default as Footer } from'./Footer'